version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
      
  web:
    build: ./infra/nginx
    ports:
      - ${WEB_PORT:-443}:443
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/localhost.pem:/etc/nginx/conf.d/localhost.pem
      - ./infra/nginx/localhost-key.pem:/etc/nginx/conf.d/localhost-key.pem
    working_dir: /data

  db:
      build: ./infra/mysql 
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
        MYSQL_USER: phper
        MYSQL_PASSWORD: password

      volumes:
        - db-store:/var/lib/mysql
volumes:
  db-store:
